name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          # прокидываем repo variables в Vite
          VITE_API_BASE: ${{ vars.PUBLIC_API_BASE }}
          VITE_WS_BASE:  ${{ vars.PUBLIC_WS_BASE }}
          # базовый путь для GitHub Pages (например `/bura-miniapp/`)
          BASE: ${{ vars.PUBLIC_BASE_PATH }}
        run: |
          # если используешь Vite, выставим base через CLI env
          echo "VITE_APP_BASE=${BASE}"
          npm run build -- --base "${BASE:-/}"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist
